CREATE TABLE PRODUCT(
PID VARCHAR(20) PRIMARY KEY,
FOOD VARCHAR(50),
FLAVOR VARCHAR(50),
PRICE DECIMAL(6,2)
);

SELECT * FROM PRODUCT;

INSERT ALL
INTO PRODUCT VALUES ('20-BC-C-10','Chocolate','Cake',8.95)
INTO PRODUCT VALUES ('20-BC-L-10','Lemon','Cake',8.95)
INTO PRODUCT VALUES ('20-CA-7.5','Casino','Cake',15.95)
INTO PRODUCT VALUES ('24-8x10','Opera','Cake',15.95)
INTO PRODUCT VALUES ('25-STR-9','Strawberry','Cake',11.95)
INTO PRODUCT VALUES ('26-8x10','Truffle','Cake',15.95)
INTO PRODUCT VALUES ('45-CH','Chocolate','Eclair',3.25)
INTO PRODUCT VALUES ('45-CO','Coffee','Eclair',3.50)
INTO PRODUCT VALUES ('45-VA','Vanilla','Eclair',3.25)
INTO PRODUCT VALUES ('46-11','Napoleon','Cake',13.49)
INTO PRODUCT VALUES ('90-ALM-I','Almond','Tart',3.75)
INTO PRODUCT VALUES ('90-APIE-10','Apple','Pie',5.25)
INTO PRODUCT VALUES ('90-APP-11','Apple','Tart',3.25)
INTO PRODUCT VALUES ('90-APR-PF','Apricot','Tart',3.25)
INTO PRODUCT VALUES ('90-BER-11','Berry','Tart',3.25)
INTO PRODUCT VALUES ('90-BLK-PF','Blackberry','Tart',3.25)
INTO PRODUCT VALUES ('90-BLU-11','Blueberry','Tart',3.25)
INTO PRODUCT VALUES ('90-CH-PF','Chocolate','Tart',3.75)

SELECT * FROM DUAL;

SELECT * FROM PRODUCT;

UPDATE PRODUCT
SET PRICE = 32.00
WHERE PID='24-8x10';

UPDATE PRODUCT
SET PRICE = PRICE * 1.10
WHERE FLAVOR='Eclair' AND FOOD LIKE 'C%';

SELECT * FROM PRODUCT;

DELETE FROM PRODUCT
WHERE FOOD='Blueberry';

SELECT * FROM PRODUCT;

COMMIT;

INSERT INTO PRODUCT VALUES ('90-ALM-I','Almond','Tart',3.75);

SELECT * FROM PRODUCT;

ROLLBACK;

INSERT INTO PRODUCT VALUES ('90-ALM-I','Almond','Tart',3.75);

SAVEPOINT A;

DELETE FROM PRODUCT;

SELECT * FROM PRODUCT;

ROLLBACK TO A;

SELECT * FROM PRODUCT;

COMMIT;

SELECT *
FROM PRODUCT
WHERE PRICE=3.25 OR (FOOD='Apple' AND FLAVOR='Tart');

SELECT *
FROM PRODUCT
WHERE PRICE=3.25 AND FOOD LIKE '%e%';

SELECT *
FROM PRODUCT
WHERE FOOD LIKE 'V%' OR FOOD LIKE 'N%' OR FOOD LIKE 'T%';

SELECT DISTINCT FLAVOR FROM PRODUCT;

SELECT * FROM PRODUCT ORDER BY PRICE ASC;

ALTER TABLE PRODUCT ADD EXPIRY_DATE DATE;

UPDATE PRODUCT SET EXPIRY_DATE = SYSDATE + 5;

SELECT * FROM PRODUCT;