CREATE TABLE SAILORS (
SAILOR_ID VARCHAR2(10) PRIMARY KEY,
SAILOR_NAME VARCHAR2(50) NOT NULL,
RATING NUMBER(2),
DATE_OF_BIRTH DATE
);
CREATE TABLE SAILORS (
SAILOR_ID VARCHAR2(10) PRIMARY KEY,
SAILOR_NAME VARCHAR2(50) NOT NULL,
RATING NUMBER(2),
DATE_OF_BIRTH DATE
);
CREATE TABLE TOURISTS (
TOURIST_ID VARCHAR2(10) PRIMARY KEY,
TOURIST_NAME VARCHAR2(50) NOT NULL,
ADDRESS VARCHAR2(100),
DATE_OF_BIRTH DATE,
PHONE VARCHAR2(15)
);
CREATE TABLE RESERVATION (
RESERVATION_ID VARCHAR2(10) PRIMARY KEY,
TOURIST_ID VARCHAR2(10),
BOAT_ID VARCHAR2(10),
SAILOR_ID VARCHAR2(10),
RESERVATION_DATE DATE,
SAIL_DATE DATE,
NUMBER_OF_PEOPLE NUMBER(3),

FOREIGN KEY (TOURIST_ID) REFERENCES TOURISTS(TOURIST_ID),
FOREIGN KEY (BOAT_ID) REFERENCES BOATS(BOAT_ID),
FOREIGN KEY (SAILOR_ID) REFERENCES SAILORS(SAILOR_ID)
);
CREATE TABLE PAYMENT (
PAYMENT_ID VARCHAR2(10) PRIMARY KEY,
RESERVATION_ID VARCHAR2(10),
PAYMENT_AMOUNT NUMBER(10,2),
PAYMENT_DATE DATE,
PAYMENT_MODE VARCHAR2(20),
PAYMENT_STATUS VARCHAR2(20),

FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATION(RESERVATION_ID)
);
SELECT * FROM BOATS;
SELECT * FROM SAILORS;
SELECT * FROM TOURISTS;
SELECT * FROM RESERVATION;
SELECT * FROM PAYMENT;

SELECT DISTINCT * 
FROM BOATS 
WHERE BOAT_ID IN (
SELECT BOAT_ID 
FROM RESERVATION 
WHERE EXTRACT(MONTH FROM RESERVATION_DATE) = EXTRACT(MONTH FROM SYSDATE)
);

SELECT TOURIST_ID, TOURIST_NAME
FROM TOURISTS
WHERE TOURIST_ID IN (
SELECT TOURIST_ID
FROM RESERVATION
WHERE SAIL_DATE = LAST_DAY(SAIL_DATE)
);

SELECT *
FROM BOATS
WHERE BOAT_ID NOT IN (
SELECT BOAT_ID
FROM RESERVATION
);

SELECT TOURIST_ID, TOURIST_NAME
FROM TOURISTS
WHERE TOURIST_ID IN (
SELECT TOURIST_ID
FROM RESERVATION
GROUP BY TOURIST_ID, RESERVATION_DATE
HAVING COUNT(*) > 1
);

SELECT *
FROM BOATS
WHERE BOAT_ID IN (
SELECT BOAT_ID
FROM RESERVATION
GROUP BY BOAT_ID
HAVING COUNT(*) >= ALL (
SELECT COUNT(*)
FROM RESERVATION
GROUP BY BOAT_ID
)
);

SELECT DISTINCT TOURIST_ID
FROM RESERVATION
WHERE BOAT_ID IN (
SELECT BOAT_ID
FROM BOATS
WHERE PRICE_PER_SEAT > (
SELECT AVG(PRICE_PER_SEAT)
FROM BOATS
)
);

SELECT S.RATING, AVG(P.PAYMENT_AMOUNT)
FROM SAILORS S
JOIN RESERVATION R ON S.SAILOR_ID = R.SAILOR_ID
JOIN PAYMENT P ON R.RESERVATION_ID = P.RESERVATION_ID
WHERE P.PAYMENT_STATUS = 'PAID'
GROUP BY S.RATING;

SELECT B.BOAT_NAME, SUM(P.PAYMENT_AMOUNT)
FROM BOATS B
JOIN RESERVATION R ON B.BOAT_ID = R.BOAT_ID
JOIN PAYMENT P ON R.RESERVATION_ID = P.RESERVATION_ID
WHERE R.TOURIST_ID = 'T001'
AND P.PAYMENT_STATUS = 'PAID'
GROUP BY B.BOAT_NAME
HAVING SUM(P.PAYMENT_AMOUNT) > (
SELECT MAX(PAYMENT_AMOUNT)
FROM PAYMENT
);

SELECT T.*, R.RESERVATION_ID, B.BOAT_NAME
FROM TOURISTS T
JOIN RESERVATION R ON T.TOURIST_ID = R.TOURIST_ID
JOIN BOATS B ON R.BOAT_ID = B.BOAT_ID
WHERE R.BOAT_ID IN (
SELECT BOAT_ID
FROM RESERVATION
GROUP BY BOAT_ID
HAVING COUNT(*) <= ALL (
SELECT COUNT(*)
FROM RESERVATION
GROUP BY BOAT_ID
)
);

SELECT T.TOURIST_ID, T.TOURIST_NAME, R.RESERVATION_ID
FROM TOURISTS T
JOIN RESERVATION R ON T.TOURIST_ID = R.TOURIST_ID
JOIN BOATS B ON R.BOAT_ID = B.BOAT_ID
WHERE B.BOAT_TYPE IN ('LUX','CAR','CRU')
GROUP BY T.TOURIST_ID, T.TOURIST_NAME, R.RESERVATION_ID
HAVING COUNT(DISTINCT B.BOAT_TYPE) = 3;

SELECT B.*, R.RESERVATION_ID
FROM BOATS B
LEFT JOIN RESERVATION R
ON B.BOAT_ID = R.BOAT_ID;

SELECT TOURIST_ID, TOURIST_NAME
FROM TOURISTS T
WHERE (
SELECT COUNT(*)
FROM RESERVATION R
WHERE R.TOURIST_ID = T.TOURIST_ID
) > (
SELECT AVG(COUNT(*))
FROM RESERVATION
GROUP BY TOURIST_ID
);

SELECT BOAT_ID
FROM RESERVATION
UNION
SELECT BOAT_ID
FROM BOATS
WHERE PRICE_PER_SEAT > (
SELECT AVG(PRICE_PER_SEAT)
FROM BOATS
);

SELECT *
FROM TOURISTS
MINUS
SELECT T.*
FROM TOURISTS T
JOIN RESERVATION R
ON T.TOURIST_ID = R.TOURIST_ID;

SELECT *
FROM BOATS
WHERE COLOUR IN (
SELECT COLOUR
FROM BOATS
WHERE BOAT_TYPE IN ('LUX','CRU')
);